### ISSUE TITLE
Regression in 2.2.2: can't run the attester-maven-plugin when Sublime Text is running with the project folder open

### ISSUE THREAD

**Issue by jakub-g** [attester/attester-maven-plugin#10]
When I try to run maven build on my machine while Sublime Text is running, I get the following exception

```
[INFO] --- attester-maven-plugin:2.2.2:test (default) @ myproject ---
[INFO] Extracting artifact com.ariatemplates.attester:attester:zip:project:2.2.2 to d:\git\myproject\target\com.ariatemplates.attester-attester-2.2.2-project
[ERROR] An exception occurred while extracting the com.ariatemplates.attester:attester:zip:project:2.2.2 artifact.
java.lang.Exception: Failed to rename directory d:\git\myproject\target\extract2824396073130557478.tmp to d:\git\myproject\target\com.ariatemplates.attester-attester-2.2.
2-project.
        at com.ariatemplates.attester.maven.ArtifactExtractor.inplaceExtractDependency(ArtifactExtractor.java:140)
        at com.ariatemplates.attester.maven.RunAttester.extractDependency(RunAttester.java:283)
        at com.ariatemplates.attester.maven.RunAttester.extractAttester(RunAttester.java:296)
        at com.ariatemplates.attester.maven.RunAttester.execute(RunAttester.java:302)
        at com.ariatemplates.attester.maven.RunTests.execute(RunTests.java:105)
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:101)
```

Everything's fine when I close Sublime. 

I checked with Unlocker that Sublime on Windows does create a lock when you open a folder with it, which is probably why the renaming of the file fails.

Note BTW this problem with Sublime is manifesting itself also in other cases... Like when you switch git branch and git wants to delete some files, Sublime prevents it from being deleted

**Comment by divdavem** [comment]
I suppose the problem happens when `mvn clean` tries to delete the `target` directory, doesn't it?
This is a problem in Sublime, which should probably not be fixed in attester.

However, if you want to prevent attester-maven-plugin from extracting files and renaming a folder at build time, you can manually copy the extracted files to a known fixed location and set the [attesterPath](http://attester.github.io/attester-maven-plugin/test-mojo.html#attesterPath) parameter through the <code>com.ariatemplates.attester.path</code> property in the maven command line (with `-Dcom.ariatemplates.attester.path=...`) or in the [maven settings](http://maven.apache.org/ref/2.2.1/maven-settings/settings.html) (by adding a profile enabled by default which contains `<com.ariatemplates.attester.path>...</com.ariatemplates.attester.path>`)
