### ISSUE TITLE
Corrupted attester tmp directory

### ISSUE THREAD

**Issue by ihabibi** [attester/attester-maven-plugin#8]
Hello,

I have currently integrated attester plugin into 1A UI build process to facilitate UI test-driven development.
However, I notice that during some random circumstances the extracted attester directory is corrupted on the server and has caused all pull requests being rejected.

Here's the log:
[ERROR] Failed to execute goal com.ariatemplates.attester:attester-maven-plugin:1.5.0:test (default) on project aodb_ui: Execution default of goal com.ariatemplates.attester:attester-maven-plugin:1.5.0:test failed: Failed to find or extract attester: Could not find file: /tmp/com.ariatemplates.attester-attester-1.5.0-project/attester/bin/attester.js -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal com.ariatemplates.attester:attester-maven-plugin:1.5.0:test (default) on project aodb_ui: Execution default of goal com.ariatemplates.attester:attester-maven-plugin:1.5.0:test failed: Failed to find or extract attester
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:224)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:120)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:355)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:155)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:584)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:216)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:160)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.plugin.PluginExecutionException: Execution default of goal com.ariatemplates.attester:attester-maven-plugin:1.5.0:test failed: Failed to find or extract attester
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:143)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
	... 19 more
Caused by: java.lang.RuntimeException: Failed to find or extract attester
	at com.ariatemplates.attester.maven.RunAttester.extractDependency(RunAttester.java:277)
	at com.ariatemplates.attester.maven.RunAttester.extractAttester(RunAttester.java:283)
	at com.ariatemplates.attester.maven.RunAttester.execute(RunAttester.java:289)
	at com.ariatemplates.attester.maven.RunTests.execute(RunTests.java:105)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:132)
	... 20 more
Caused by: java.io.FileNotFoundException: Could not find file: /tmp/com.ariatemplates.attester-attester-1.5.0-project/attester/bin/attester.js
	at com.ariatemplates.attester.maven.RunAttester.extractDependency(RunAttester.java:274)
	... 24 more

Quick investigation reveals that this issue may be linked to parallel builds on the server. I can simply remove the tmp directory but this won't completely solve the root cause.

I have 2 proposals to overcome the issue:
* extract attester framework all the time by prefixing directory with timestamp or random values and delete it after test completion
or
* enhance the logic to validate attester directory is available and not corrupted else override it

Could you please advise if you can implement any of these proposals?
Thanks & Best regards,
Imam

**Comment by jakub-g** [comment]
Hi,

I am no maven expert at all but looking at the description you provided it seems this issue could happen with virtually any maven dependency, if the time between its extraction at the build time and actual usage is big enough. 

If it's an issue of multiple parallel builds on the same machine writing to a shared temp folder I guess nothing could be done other than better controlling the build environment and coordinating with the platform team.

**Comment by vcarle** [comment]
Hi,

Actually it's not a problem of parallel builds, or bad timing within one single build, but a matter of permanency of files in the /tmp folder on the long term.

The issue is that in ArtifactExtractor we only check the existence of the output directory, and if it does exist, we assume the zip was already extracted and all the files are already present on the machine, and we move to the next step.

This check is not enough. Since the extraction is done in the /tmp folder which we do not control, we have no guarantee that the extracted folder will remain consistent. Some of the files can be deleted by another process (e.g. when /tmp is full, or when the machine is rebooted). In particular, it is possible that the folder still exists but does not contain any file.

This is what happened for my project, I can see on the build machine that I do have /tmp/com.ariatemplates.attester-attester-1.3.0-project/attester folder, but it contains no file at all. Then the build fails with the same stack as the one logged by ihabibi.

A simple workaround could be to systematically extract the zip in a new folder (I don't think it would lead to a big overhead).

**Comment by divdavem** [comment]
Hello,

@ihabibi @vcarle Thank you for reporting this issue.

I think extracting attester in a sub-directory of the `target` (`maven.build.directory`) directory of the current maven project would solve this issue.
`mvn clean` removes the `target` directory, so, this way, to be sure that the attester directory is not corrupted, it is always possible to run `mvn clean` (and there is less probability for it to get corrupted there than in `/tmp`).

I have opened [this pull request](https://github.com/attester/attester-maven-plugin/pull/9) to implement this by default, with an option to configure the directory (`attesterExtractionParentDirectory`).

@ihabibi @vcarle @jakub-g  What do you think of this solution?

**Comment by vcarle** [comment]
Seems good to me, thanks for the fix :)

**Comment by ihabibi** [comment]
Correct, the fix seems to solve the root-cause :) Thanks!

**Comment by divdavem** [comment]
@vcarle @ihabibi @jakub-g Thank you for your review. I have released attester-maven-plugin version 2.2.2 which contains the fix.
